<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $services = [
            [
                'slug' => 'kitchen',
                'title' => [
                    'fr' => 'Cuisines en Aluminium',
                    'en' => 'Aluminum Kitchens',
                    'ar' => 'مطابخ الألومنيوم',
                ],
                'short_description' => [
                    'fr' => 'Des cuisines modernes et durables en aluminium de haute qualité.',
                    'en' => 'Modern and durable kitchens made from high-quality aluminum.',
                    'ar' => 'مطابخ حديثة ومتينة من الألومنيوم عالي الجودة.',
                ],
                'description' => [
                    'fr' => 'Nos cuisines en aluminium allient modernité et durabilité. Conçues sur mesure, elles offrent une résistance exceptionnelle à l\'humidité et à la chaleur, tout en étant faciles à entretenir.',
                    'en' => 'Our aluminum kitchens combine modernity and durability. Custom-designed, they offer exceptional resistance to humidity and heat while being easy to maintain.',
                    'ar' => 'تجمع مطابخنا المصنوعة من الألومنيوم بين الحداثة والمتانة. مصممة حسب الطلب، توفر مقاومة استثنائية للرطوبة والحرارة مع سهولة الصيانة.',
                ],
                'icon' => 'utensils',
                'svg_icon' => '<svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 md:w-10 md:h-10 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z"/><path d="M3 9V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v4"/><path d="M12 3v6"/><path d="M8 21v-4"/><path d="M16 21v-4"/></svg>',
                'color' => 'rose',
                'image' => 'https://www.shenghai-alu.com/product/image/_shared/news/Aluminum%20profile%20kitchen%20cabinet.jpg',
                'gallery' => [
                    'https://johnmichael.studio/cdn/shop/files/Finalist_B_1800x.jpg?v=1699548126',
                    'https://www.ateliersjacob.com/app/uploads/2022/08/ateliersjacob-9360bretonvillier-11-1-e1678800203446-1372x1071.jpg',
                    'https://acecabinetdesign.com.my/wp-content/uploads/2024/07/3.-Modern-and-Sleek-Appeal-aluminium-kitchen-cabinet.png',
                    'https://johnmichael.studio/cdn/shop/files/0033_ID_CATSKILL_NY_2.jpg?v=1674568547&width=800',
                    'https://www.rockruncabinetry.com/images/homepage/Rock-Run-Cabinetry-Aluminum-Kitchen-Cabinets.jpg',
                    'https://www.quartzjohor.com/wp-content/uploads/2024/07/Modern-Trends-in-Aluminium-Kitchen-Cabinets-l-Quartz-Johor.png',
                    'https://m.media-amazon.com/images/I/71XFYS9utIL.jpg',
                    'https://www.thecabinetstudio.ca/uploads/1/1/4/4/11440476/kitchen-1_orig.jpg',
                    'https://i.pinimg.com/474x/ca/f7/60/caf760baef54e9e3226b0042e1802aa0.jpg',
                ],
                'features' => [
                    ['fr' => 'Résistance à l\'humidité', 'en' => 'Moisture resistance', 'ar' => 'مقاومة للرطوبة'],
                    ['fr' => 'Design moderne et épuré', 'en' => 'Modern and sleek design', 'ar' => 'تصميم عصري وأنيق'],
                    ['fr' => 'Entretien facile', 'en' => 'Easy maintenance', 'ar' => 'سهولة الصيانة'],
                    ['fr' => 'Personnalisation complète', 'en' => 'Full customization', 'ar' => 'تخصيص كامل'],
                    ['fr' => 'Confort optimal', 'en' => 'Optimal comfort', 'ar' => 'راحة مثالية'],
                ],
                'materials' => [
                    ['fr' => 'Profilés aluminium', 'en' => 'Aluminum profiles', 'ar' => 'ملفات الألومنيوم'],
                    ['fr' => 'Verre trempé', 'en' => 'Tempered glass', 'ar' => 'زجاج مقسى'],
                    ['fr' => 'Quincaillerie inox', 'en' => 'Stainless hardware', 'ar' => 'أدوات من الفولاذ المقاوم للصدأ'],
                    ['fr' => 'Laquage poudre', 'en' => 'Powder coating', 'ar' => 'طلاء بودرة'],
                ],
                'specs' => [
                    ['label' => 'Épaisseur', 'value' => '1.2 - 2.0 mm'],
                    ['label' => 'Finition', 'value' => 'Mat / Brillant'],
                    ['label' => 'Couleurs', 'value' => '200+'],
                ],
                'sort_order' => 1,
            ],
            [
                'slug' => 'doors',
                'title' => [
                    'fr' => 'Portes en Aluminium',
                    'en' => 'Aluminum Doors',
                    'ar' => 'أبواب الألومنيوم',
                ],
                'short_description' => [
                    'fr' => 'Portes d\'entrée et intérieures en aluminium pour une sécurité et un style incomparables.',
                    'en' => 'Entrance and interior aluminum doors for unmatched security and style.',
                    'ar' => 'أبواب مدخل وداخلية من الألومنيوم لأمان وأناقة لا مثيل لهما.',
                ],
                'description' => [
                    'fr' => 'Nos portes en aluminium offrent une combinaison parfaite de sécurité, d\'isolation et d\'esthétique. Disponibles en plusieurs configurations et finitions.',
                    'en' => 'Our aluminum doors offer a perfect combination of security, insulation, and aesthetics. Available in multiple configurations and finishes.',
                    'ar' => 'توفر أبوابنا المصنوعة من الألومنيوم مزيجًا مثاليًا من الأمان والعزل والجمال. متوفرة بتكوينات وتشطيبات متعددة.',
                ],
                'icon' => 'door-open',
                'svg_icon' => '<svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 md:w-10 md:h-10 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>',
                'color' => 'orange',
                'image' => 'https://www.glenviewdoors.com/ExteriorAluminum/gallery/Swing-Aluminum-Exterior-Door-with-Sidelites-EAL-SWS-W6-2SL.jpg',
                'gallery' => [
                    'https://www.neuffer-windows.com/fileadmin/templates/neuffer/images/frontdoors/alu-front-door-grey-sidelight.jpg',
                    'https://domadeco.com/media/catalog/product/cache/b99dbb5d5cb963a331f848f480bf280d/b/a/basic-nowe.jpg',
                    'https://www.glenviewdoors.com/ExteriorAluminum/doors/big/EAL-SWS-W6-DD.jpg',
                    'https://dash.iwantthatdoor.com//Blogs/Images/1747280302_aluminum-swing-doors.png',
                    'https://cdn-fdjec.nitrocdn.com/aRVTYhFIQPPvbZUjFkrAOFlOqBUcIUET/assets/images/optimized/rev-b68fae8/proaluminium.co.za/wp-content/uploads/2018/08/R16.jpg',
                    'https://www.glenviewdoors.com/ExteriorAluminum/images/profiles/big/Lock-Multipoint.jpg',
                    'https://colliergroup.com/cdn/shop/files/Fleetwood-Aluminum-Doors.14web.png?v=1708107131&width=1445',
                    'https://www.neuffer-windows.com/fileadmin/templates/neuffer/images/frontdoors/alu-front-door-sidelights.jpg',
                    'https://images.thdstatic.com/productImages/8adcfa6f-7974-4b44-b0c7-bff080b811f2/svn/silver-teza-doors-commercial-doors-sf557284rhs-64_600.jpg',
                ],
                'features' => [
                    ['fr' => 'Sécurité et durabilité', 'en' => 'Security and durability', 'ar' => 'الأمان والمتانة'],
                    ['fr' => 'Puissance et résistance', 'en' => 'Power and strength', 'ar' => 'القوة والمتانة'],
                    ['fr' => 'Style et élégance', 'en' => 'Style and elegance', 'ar' => 'الأناقة والرقي'],
                    ['fr' => 'Design personnalisable', 'en' => 'Customizable design', 'ar' => 'تصميم قابل للتخصيص'],
                ],
                'materials' => [
                    ['fr' => 'Profilés aluminium', 'en' => 'Aluminum profiles', 'ar' => 'ملفات الألومنيوم'],
                    ['fr' => 'Verre trempé', 'en' => 'Tempered glass', 'ar' => 'زجاج مقسى'],
                    ['fr' => 'Quincaillerie inox', 'en' => 'Stainless hardware', 'ar' => 'أدوات من الفولاذ المقاوم للصدأ'],
                    ['fr' => 'Rupture de pont thermique', 'en' => 'Thermal break', 'ar' => 'كسر الجسر الحراري'],
                ],
                'specs' => [
                    ['label' => 'Épaisseur', 'value' => '1.4 - 2.0 mm'],
                    ['label' => 'Options verre', 'value' => '6 - 24 mm'],
                    ['label' => 'Couleurs', 'value' => '200+'],
                ],
                'sort_order' => 2,
            ],
            [
                'slug' => 'windows',
                'title' => [
                    'fr' => 'Fenêtres en Aluminium',
                    'en' => 'Aluminum Windows',
                    'ar' => 'نوافذ الألومنيوم',
                ],
                'short_description' => [
                    'fr' => 'Fenêtres performantes en aluminium pour une isolation optimale et une luminosité maximale.',
                    'en' => 'High-performance aluminum windows for optimal insulation and maximum brightness.',
                    'ar' => 'نوافذ ألومنيوم عالية الأداء لعزل مثالي وإضاءة قصوى.',
                ],
                'description' => [
                    'fr' => 'Nos fenêtres en aluminium garantissent une excellente isolation thermique et acoustique tout en maximisant l\'entrée de lumière naturelle.',
                    'en' => 'Our aluminum windows guarantee excellent thermal and acoustic insulation while maximizing natural light entry.',
                    'ar' => 'تضمن نوافذنا المصنوعة من الألومنيوم عزلًا حراريًا وصوتيًا ممتازًا مع تعظيم دخول الضوء الطبيعي.',
                ],
                'icon' => 'square',
                'svg_icon' => '<svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 md:w-10 md:h-10 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="12" y1="3" x2="12" y2="21"></line><line x1="3" y1="12" x2="21" y2="12"></line></svg>',
                'color' => 'blue',
                'image' => 'https://i0.wp.com/www.allweatheraa.com/wp-content/uploads/Series_Photos/Series_6200/All-Weather_Series-6200-Hero-Web-Res_RGB-e1681844069471.jpg?fit=1920%2C1243&ssl=1',
                'gallery' => [
                    'https://mccoymart.com/post/wp-content/webp-express/webp-images/uploads/Ultimate-Buying-Guide-Of-Aluminium-Windows-Prices-Factors-And-Choices-370x200.jpg.webp',
                    'https://www.americanwindowcompany.com/wp-content/uploads/2023/05/Aluminum-Window-1.jpg.webp',
                    'https://www.monmouthshirewindows.com/wp-content/uploads/2021/11/Ali-Window-e1664440624288.jpg',
                    'https://designpluswindows.com/wp-content/uploads/2024/03/alumunium-casement-window.png',
                    'https://capitalwindows.co.uk/wp-content/uploads/2024/02/Shot24_1690196430929-1080x675.jpg',
                    'https://www.feneste.com/wp-content/uploads/feneste-products-windows-alu-opened.webp',
                    'https://en.lesso.com/blogs/wp-content/uploads/2021/07/aluminum-alloy-window-advantages.jpg',
                    'https://www.milgard.com/sites/default/files/styles/pt_image_slide_default_phone/public/2022-12/Series_TIA1.jpg?itok=7mDjtdsy',
                    'https://www.plygem.com/wp-content/uploads/shared/2024/11/PGW_Interior_LivingRoom_SingleHungWindow_GeometicWindow_White_60_40_With_MaterialListingCard_Module_1_583x583_p223.jpg',
                ],
                'features' => [
                    ['fr' => 'Robustesse et durabilité', 'en' => 'Robustness and durability', 'ar' => 'المتانة والديمومة'],
                    ['fr' => 'Performance énergétique', 'en' => 'Energy performance', 'ar' => 'كفاءة الطاقة'],
                    ['fr' => 'Design esthétique', 'en' => 'Aesthetic design', 'ar' => 'تصميم جمالي'],
                ],
                'materials' => [
                    ['fr' => 'Profilés aluminium', 'en' => 'Aluminum profiles', 'ar' => 'ملفات الألومنيوم'],
                    ['fr' => 'Double vitrage', 'en' => 'Double glass', 'ar' => 'زجاج مزدوج'],
                    ['fr' => 'Joints EPDM', 'en' => 'EPDM seals', 'ar' => 'حشوات EPDM'],
                    ['fr' => 'Rupture de pont thermique', 'en' => 'Thermal break', 'ar' => 'كسر الجسر الحراري'],
                ],
                'specs' => [
                    ['label' => 'Épaisseur', 'value' => '1.4 - 1.8 mm'],
                    ['label' => 'Options verre', 'value' => '4+12+4 mm'],
                    ['label' => 'Couleurs', 'value' => '200+'],
                ],
                'sort_order' => 3,
            ],
            [
                'slug' => 'rolling_shutters',
                'title' => [
                    'fr' => 'Volets Roulants',
                    'en' => 'Rolling Shutters',
                    'ar' => 'شتر (ستائر دوارة)',
                ],
                'short_description' => [
                    'fr' => 'Volets roulants motorisés pour une protection et un confort au quotidien.',
                    'en' => 'Motorized rolling shutters for daily protection and comfort.',
                    'ar' => 'ستائر دوارة آلية للحماية والراحة اليومية.',
                ],
                'description' => [
                    'fr' => 'Nos volets roulants en aluminium offrent sécurité, isolation thermique et confort d\'utilisation avec options motorisées.',
                    'en' => 'Our aluminum rolling shutters offer security, thermal insulation and ease of use with motorized options.',
                    'ar' => 'توفر ستائرنا الدوارة المصنوعة من الألومنيوم الأمان والعزل الحراري وسهولة الاستخدام مع خيارات آلية.',
                ],
                'icon' => 'blinds',
                'svg_icon' => '<svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 md:w-10 md:h-10 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><line x1="3" y1="7" x2="21" y2="7"/><line x1="3" y1="11" x2="21" y2="11"/><line x1="3" y1="15" x2="21" y2="15"/><line x1="3" y1="19" x2="21" y2="19"/></svg>',
                'color' => 'purple',
                'image' => 'https://m.media-amazon.com/images/I/61fC+s2K2hL.jpg',
                'gallery' => [
                    'https://preferredwindowanddoor.com/wp-content/uploads/2019/09/rolling-shutter-door-installation.jpg',
                    'https://i.ebayimg.com/images/g/55oAAOSwCSlg3TFV/s-l1200.jpg',
                    'https://www.neuffer-windows.com/sites/us/files/img/rollershutters/front-mounted-rollershutter-angular.jpg',
                    'https://shuttersbyempire.com/cdn/shop/products/rollingshutter_3_large.jpg?v=1444665936',
                    'https://m.media-amazon.com/images/I/61spuUE0n4L._AC_UF894,1000_QL80_.jpg',
                    'https://rollingshutterschicago.com/wp-content/uploads/2019/04/1798687_1548841702035169_5711829371567172947_n.jpg',
                    'https://smartguardshutters.com/wp-content/uploads/2021/04/IMG_0704.jpg',
                    'https://5krorwxhqlpnrik.ldycdn.com/cloud/jnBpiKrqRiiSrqqlljlpi/aluminium-shutter-window.jpg',
                    'https://gulfcoastshutter.com/wp-content/uploads/2021/08/comcast.jpg',
                ],
                'features' => [
                    ['fr' => 'Sécurité renforcée', 'en' => 'Enhanced security', 'ar' => 'أمان معزز'],
                    ['fr' => 'Confort thermique', 'en' => 'Thermal comfort', 'ar' => 'راحة حرارية'],
                    ['fr' => 'Protection météo', 'en' => 'Weather protection', 'ar' => 'حماية من الطقس'],
                    ['fr' => 'Design esthétique', 'en' => 'Aesthetic design', 'ar' => 'تصميم جمالي'],
                    ['fr' => 'Tranquillité d\'esprit', 'en' => 'Peace of mind', 'ar' => 'راحة البال'],
                ],
                'materials' => [
                    ['fr' => 'Lames aluminium', 'en' => 'Aluminum slats', 'ar' => 'شرائح الألومنيوم'],
                    ['fr' => 'Isolation mousse', 'en' => 'Foam insulation', 'ar' => 'عزل رغوي'],
                    ['fr' => 'Système moteur', 'en' => 'Motor system', 'ar' => 'نظام المحرك'],
                    ['fr' => 'Rails de guidage', 'en' => 'Guide rails', 'ar' => 'قضبان التوجيه'],
                ],
                'specs' => [
                    ['label' => 'Épaisseur lames', 'value' => '0.5 - 0.8 mm'],
                    ['label' => 'Largeur lames', 'value' => '37 - 55 mm'],
                    ['label' => 'Couleurs', 'value' => '50+'],
                ],
                'sort_order' => 4,
            ],
            [
                'slug' => 'railings',
                'title' => [
                    'fr' => 'Garde-corps',
                    'en' => 'Railings',
                    'ar' => 'الدرابزين',
                ],
                'short_description' => [
                    'fr' => 'Garde-corps et balustrades en aluminium pour sécurité et esthétique.',
                    'en' => 'Aluminum railings and balustrades for safety and aesthetics.',
                    'ar' => 'درابزين وحواجز من الألومنيوم للأمان والجمال.',
                ],
                'description' => [
                    'fr' => 'Nos garde-corps en aluminium et verre combinent sécurité maximale et design contemporain pour balcons, terrasses et escaliers.',
                    'en' => 'Our aluminum and glass railings combine maximum safety and contemporary design for balconies, terraces and stairs.',
                    'ar' => 'تجمع درابزيناتنا المصنوعة من الألومنيوم والزجاج بين الأمان الأقصى والتصميم المعاصر للشرفات والتراسات والسلالم.',
                ],
                'icon' => 'fence',
                'svg_icon' => '<svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 md:w-10 md:h-10 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22V8"/><path d="M5 12H2a10 10 0 0 0 20 0h-3"/><path d="M22 8l-2 2-2-2"/><path d="M6 8l-2 2-2-2"/><path d="M6 22v-4"/><path d="M18 22v-4"/></svg>',
                'color' => 'green',
                'image' => 'https://www.newtechwood.com/wp-content/uploads/2022/03/IMG_1832-scaled.jpg',
                'gallery' => [
                    'https://www.archmetalsfl.com/Content/files/Products/Railing.jpg',
                    'https://www.olddutchman.com/wp-content/uploads/2014/06/railings-exterior-aluminum-512x384.jpg',
                    'https://www.williamsrailing.com/filesimages/Homepage/img_gate.jpg',
                    'https://images.trex.com/is/image/trexcompany/sel-pinehurst-006-pg-decking-sig-alum-bk-railing-sq-bal-wt-comp-sleeves-PG010616SS64:Article-Image-Main?ts=1764880342814&dpr=on,2.625',
                    'https://duradek.com/wp-content/uploads/Aluminum-Railings-Durarail-bg.jpg',
                    'https://rdirail.com/wp-content/uploads/2025/02/73056825-73056827-RDIRailing-AvalonAluminumRail-MatteBlack-Scene02.jpg',
                    'https://www.vistarailings.com/wp-content/uploads/2020/10/Picket_AlumRailpage2020_588x527.jpg',
                    'https://dolleusa.com/cdn/shop/products/anthracite3_1500x.jpg?v=1631644004',
                    'https://www.decksdirect.com/media/catalog/category/revival-plus-vertical-aluminum-railing_1.webp',
                ],
                'features' => [
                    ['fr' => 'Solidité garantie', 'en' => 'Guaranteed strength', 'ar' => 'متانة مضمونة'],
                    ['fr' => 'Élégance moderne', 'en' => 'Modern elegance', 'ar' => 'أناقة عصرية'],
                    ['fr' => 'Installation facile', 'en' => 'Easy installation', 'ar' => 'تركيب سهل'],
                    ['fr' => 'Sécurité optimale', 'en' => 'Optimal security', 'ar' => 'أمان مثالي'],
                    ['fr' => 'Polyvalence', 'en' => 'Versatility', 'ar' => 'تعدد الاستخدامات'],
                    ['fr' => 'Intégration harmonieuse', 'en' => 'Harmonious integration', 'ar' => 'تكامل متناغم'],
                ],
                'materials' => [
                    ['fr' => 'Profilés aluminium', 'en' => 'Aluminum profiles', 'ar' => 'ملفات الألومنيوم'],
                    ['fr' => 'Verre trempé', 'en' => 'Tempered glass', 'ar' => 'زجاج مقسى'],
                    ['fr' => 'Fixations inox', 'en' => 'Stainless fittings', 'ar' => 'تثبيتات من الفولاذ المقاوم للصدأ'],
                    ['fr' => 'Laquage poudre', 'en' => 'Powder coating', 'ar' => 'طلاء بودرة'],
                ],
                'specs' => [
                    ['label' => 'Épaisseur', 'value' => '1.5 - 2.5 mm'],
                    ['label' => 'Options verre', 'value' => '8 - 12 mm'],
                    ['label' => 'Couleurs', 'value' => '200+'],
                ],
                'sort_order' => 5,
            ],
            [
                'slug' => 'pergola',
                'title' => [
                    'fr' => 'Pergolas',
                    'en' => 'Pergolas',
                    'ar' => 'البرجولات',
                ],
                'short_description' => [
                    'fr' => 'Pergolas bioclimatiques en aluminium pour profiter de votre extérieur toute l\'année.',
                    'en' => 'Bioclimatic aluminum pergolas to enjoy your outdoor space all year round.',
                    'ar' => 'برجولات بيومناخية من الألومنيوم للاستمتاع بمساحتك الخارجية طوال العام.',
                ],
                'description' => [
                    'fr' => 'Nos pergolas en aluminium créent des espaces de vie extérieurs élégants avec contrôle de l\'ombre et de la ventilation.',
                    'en' => 'Our aluminum pergolas create elegant outdoor living spaces with shade and ventilation control.',
                    'ar' => 'تخلق برجولاتنا المصنوعة من الألومنيوم مساحات معيشة خارجية أنيقة مع التحكم في الظل والتهوية.',
                ],
                'icon' => 'tent',
                'svg_icon' => '<svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 md:w-10 md:h-10 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 22V6"/><path d="M20 22V6"/><path d="M2 6h20"/><path d="M2 10h20"/><path d="M12 6v16"/></svg>',
                'color' => 'amber',
                'image' => 'https://m.media-amazon.com/images/I/81jVmYIrD7L._AC_UF894,1000_QL80_.jpg',
                'gallery' => [
                    'http://hideawayscreen.com/cdn/shop/files/hideaway-pergola-black-pergola-slatted-33139981713581.jpg?v=1722798548&width=2048',
                    'http://oakcitycustoms.com/cdn/shop/files/Pergola1_d8192c52-d0ff-447c-8687-4727821dba5c.png?v=1707057488',
                    'https://m.media-amazon.com/images/I/91VWA1HiTeL._AC_UF894,1000_QL80_.jpg',
                    'https://peacefulpatios.com/cdn/shop/files/FreestandingAluminumPergola4_1500x.jpg?v=1702060322',
                    'https://images.thdstatic.com/productImages/ff32fe8c-20eb-4d87-acbb-1cd3a902a2ae/svn/gray-domi-outdoor-living-pergolas-lgmf1630-g-us-4f_600.jpg',
                    'https://assets.alliedoutdoorsolutions.com/assets/images/hero/AluminumPatio_Hero-67241ef0268ff3cfccd54e01f42e673e.jpg',
                    'https://sunsetpergolakits.com/cdn/shop/products/SPK-Trad-Attached-SingleUpTo16x16-White_e660db05-4da4-43f4-961f-66a8daee75d5_700x700.jpg?v=1741043539',
                    'https://ak1.ostkcdn.com/images/products/is/images/direct/62f8d89204913614500ab82e085c9f575eee0411/PURPLE-LEAF-Gray-Louvered-Pergola-Outdoor-Aluminum-Pergola-with-Adjustable-Roof-for-Patio-Grey-Hardtop-Gazebo.jpg?impolicy=medium',
                    'https://paragon-outdoor.com/cdn/shop/files/frontview_lifestyle_e8660d9c-271f-4a25-87f4-e8c93189492c.jpg?v=1751989737&width=1946',
                ],
                'features' => [
                    ['fr' => 'Robustesse et durabilité', 'en' => 'Robustness and durability', 'ar' => 'المتانة والديمومة'],
                    ['fr' => 'Esthétique raffinée', 'en' => 'Refined aesthetics', 'ar' => 'جمالية راقية'],
                    ['fr' => 'Sans entretien', 'en' => 'No maintenance', 'ar' => 'بدون صيانة'],
                    ['fr' => 'Allié de l\'aménagement', 'en' => 'Layout ally', 'ar' => 'حليف التصميم'],
                    ['fr' => 'Tranquillité d\'esprit', 'en' => 'Peace of mind', 'ar' => 'راحة البال'],
                ],
                'materials' => [
                    ['fr' => 'Poutres aluminium', 'en' => 'Aluminum beams', 'ar' => 'عوارض الألومنيوم'],
                    ['fr' => 'Toiture polycarbonate', 'en' => 'Polycarbonate roof', 'ar' => 'سقف بولي كربونات'],
                    ['fr' => 'Système drainage', 'en' => 'Drainage system', 'ar' => 'نظام الصرف'],
                    ['fr' => 'Éclairage LED', 'en' => 'LED lighting', 'ar' => 'إضاءة LED'],
                ],
                'specs' => [
                    ['label' => 'Épaisseur', 'value' => '2.0 - 3.0 mm'],
                    ['label' => 'Portée max', 'value' => '6 m'],
                    ['label' => 'Couleurs', 'value' => '100+'],
                ],
                'sort_order' => 6,
            ],
            [
                'slug' => 'sun_breakers',
                'title' => [
                    'fr' => 'Brise-soleil',
                    'en' => 'Sun Breakers',
                    'ar' => 'كاسرات الشمس',
                ],
                'short_description' => [
                    'fr' => 'Brise-soleil en aluminium pour contrôler la lumière et réduire la chaleur.',
                    'en' => 'Aluminum sun breakers to control light and reduce heat.',
                    'ar' => 'كاسرات شمس من الألومنيوم للتحكم في الضوء وتقليل الحرارة.',
                ],
                'description' => [
                    'fr' => 'Nos brise-soleil orientables permettent un contrôle optimal de la luminosité et contribuent à l\'efficacité énergétique du bâtiment.',
                    'en' => 'Our adjustable sun breakers allow optimal brightness control and contribute to building energy efficiency.',
                    'ar' => 'تتيح كاسرات الشمس القابلة للتوجيه لدينا التحكم الأمثل في السطوع وتساهم في كفاءة الطاقة للمبنى.',
                ],
                'icon' => 'sun',
                'svg_icon' => '<svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 md:w-10 md:h-10 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>',
                'color' => 'yellow',
                'image' => 'https://image.made-in-china.com/2f0j00yKTVFEaGhzow/Aluminum-Exterior-Single-Bank-Sun-Breaker-Louver-Aluminium.webp',
                'gallery' => [
                    'http://www.bi-brent.com/wp-content/uploads/2019/06/Sunbreakers.jpg',
                    'https://www.alcirclebiz.com//Uploads/ProductImage/18377/aluminiumsunbreaker.jpg',
                    'https://sc04.alicdn.com/kf/HTB1Z6BuePgy_uJjSZTEq6AYkFXas.jpg',
                    'https://lookaside.instagram.com/seo/google_widget/crawler/?media_id=3095101980329260423',
                    'https://koraluminyum.com.tr/slides/products/63086b33c6e07.jpg',
                    'https://img.archiexpo.com/images_ae/photo-mg/65037-10329093.jpg',
                    'https://aluum.com/wp-content/uploads/2025/03/Alum-Horizontal-Sunbreaker.jpg',
                    'https://www.sistemal.com/en/wp-content/uploads/2025/11/what-is-a-sun-breaker-panel-what-is-the-purpose-of-a-sun-breaker-system.webp',
                    'https://dscons-gh.com/wp-content/uploads/2022/05/Sun-Breakers-300x300.jpg',
                ],
                'features' => [
                    ['fr' => 'Confort thermique', 'en' => 'Thermal comfort', 'ar' => 'راحة حرارية'],
                    ['fr' => 'Robustesse', 'en' => 'Robustness', 'ar' => 'المتانة'],
                    ['fr' => 'Design moderne', 'en' => 'Modern design', 'ar' => 'تصميم عصري'],
                    ['fr' => 'Sans entretien', 'en' => 'No maintenance', 'ar' => 'بدون صيانة'],
                    ['fr' => 'Intégration harmonieuse', 'en' => 'Harmonious integration', 'ar' => 'تكامل متناغم'],
                    ['fr' => 'Économies d\'énergie', 'en' => 'Energy savings', 'ar' => 'توفير الطاقة'],
                ],
                'materials' => [
                    ['fr' => 'Lames aluminium', 'en' => 'Aluminum blades', 'ar' => 'شفرات الألومنيوم'],
                    ['fr' => 'Système pivot', 'en' => 'Pivot system', 'ar' => 'نظام المحور'],
                    ['fr' => 'Mécanisme de contrôle', 'en' => 'Control mechanism', 'ar' => 'آلية التحكم'],
                    ['fr' => 'Laquage poudre', 'en' => 'Powder coating', 'ar' => 'طلاء بودرة'],
                ],
                'specs' => [
                    ['label' => 'Largeur lames', 'value' => '100 - 300 mm'],
                    ['label' => 'Angle', 'value' => '0 - 90°'],
                    ['label' => 'Couleurs', 'value' => '200+'],
                ],
                'sort_order' => 7,
            ],
            [
                'slug' => 'mosquito_nets',
                'title' => [
                    'fr' => 'Moustiquaires',
                    'en' => 'Mosquito Nets',
                    'ar' => 'شبكات البعوض',
                ],
                'short_description' => [
                    'fr' => 'Moustiquaires en aluminium pour une protection efficace contre les insectes.',
                    'en' => 'Aluminum mosquito nets for effective insect protection.',
                    'ar' => 'شبكات بعوض من الألومنيوم لحماية فعالة من الحشرات.',
                ],
                'description' => [
                    'fr' => 'Nos moustiquaires en aluminium offrent une protection discrète et efficace tout en laissant passer l\'air et la lumière.',
                    'en' => 'Our aluminum mosquito nets offer discreet and effective protection while allowing air and light to pass through.',
                    'ar' => 'توفر شبكات البعوض المصنوعة من الألومنيوم لدينا حماية سرية وفعالة مع السماح بمرور الهواء والضوء.',
                ],
                'icon' => 'grid-3x3',
                'svg_icon' => '<svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 md:w-10 md:h-10 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18"/><path d="M3 15h18"/><path d="M9 3v18"/><path d="M15 3v18"/></svg>',
                'color' => 'teal',
                'image' => 'https://www.windowo.com/data/thumb_cache/_data_prod_img_zanzariera-magnetica-fissa-in-alluminio-sagittario-effezeta_jpg_r_1000_1000.jpg',
                'gallery' => [
                    'https://m.media-amazon.com/images/I/61+JBAHEKDL._AC_UF894,1000_QL80_.jpg',
                    'https://m.media-amazon.com/images/I/61-8iM3yAJL.jpg',
                    'https://www.windowo.it/data/image/Bettio/zanzariera-telaio-fisso-bettio.jpg',
                    'https://cpimg.tistatic.com/05041284/b/5/Aluminium-Mosquito-Net.jpg',
                    'https://m.media-amazon.com/images/I/716ItnVos7L._AC_UF894,1000_QL80_.jpg',
                    'https://s.alicdn.com/@sc04/kf/H83c2fc625a4f4efc9f7e20766c559f62X/Aluminum-Alloy-Frame-Mosquito-Net-Folding-Pleated-Mesh-Sliding-Door-Trackless-Pleated-Insect-Window-Door-Screen-for-Home.png',
                    'https://hts-alu.com/wp-content/uploads/2024/02/Sliding-Window-Mosquito-Net-Aluminium-Profile-1.webp',
                    'https://iprnrwxhlqin5q.ldycdn.com/cloud/lpBqoKqkSRqikjkjrpko/Aluminum-Fly-Screen-Door.jpg',
                    'https://rajaluminium.com/images/product/IMG_20220930_183624-930202261607AM.jpg',
                ],
                'features' => [
                    ['fr' => 'Protection efficace', 'en' => 'Effective protection', 'ar' => 'حماية فعالة'],
                    ['fr' => 'Robustesse', 'en' => 'Robustness', 'ar' => 'المتانة'],
                    ['fr' => 'Installation facile', 'en' => 'Easy installation', 'ar' => 'تركيب سهل'],
                    ['fr' => 'Confort optimal', 'en' => 'Optimal comfort', 'ar' => 'راحة مثالية'],
                    ['fr' => 'Design discret', 'en' => 'Discreet design', 'ar' => 'تصميم سري'],
                    ['fr' => 'Tranquillité d\'esprit', 'en' => 'Peace of mind', 'ar' => 'راحة البال'],
                ],
                'materials' => [
                    ['fr' => 'Cadre aluminium', 'en' => 'Aluminum frame', 'ar' => 'إطار الألومنيوم'],
                    ['fr' => 'Toile fibre de verre', 'en' => 'Fiberglass mesh', 'ar' => 'شبكة الألياف الزجاجية'],
                    ['fr' => 'Joints brosse', 'en' => 'Brush seals', 'ar' => 'حشوات فرشاة'],
                    ['fr' => 'Mécanisme enrouleur', 'en' => 'Roller mechanism', 'ar' => 'آلية التدوير'],
                ],
                'specs' => [
                    ['label' => 'Densité toile', 'value' => '18x16'],
                    ['label' => 'Profilé cadre', 'value' => '25 - 45 mm'],
                    ['label' => 'Couleurs', 'value' => '30+'],
                ],
                'sort_order' => 8,
            ],
            [
                'slug' => 'space_design',
                'title' => [
                    'fr' => 'Aménagement d\'espaces',
                    'en' => 'Space Design',
                    'ar' => 'تصميم المساحات',
                ],
                'short_description' => [
                    'fr' => 'Cloisons et séparations en aluminium pour organiser vos espaces intérieurs.',
                    'en' => 'Aluminum partitions and dividers to organize your interior spaces.',
                    'ar' => 'فواصل وحواجز من الألومنيوم لتنظيم مساحاتك الداخلية.',
                ],
                'description' => [
                    'fr' => 'Nos solutions d\'aménagement en aluminium et verre permettent de créer des espaces modulables tout en préservant la luminosité.',
                    'en' => 'Our aluminum and glass layout solutions allow you to create modular spaces while preserving brightness.',
                    'ar' => 'تتيح لك حلول التخطيط المصنوعة من الألومنيوم والزجاج إنشاء مساحات قابلة للتعديل مع الحفاظ على السطوع.',
                ],
                'icon' => 'layout-grid',
                'svg_icon' => '<svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 md:w-10 md:h-10 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/></svg>',
                'color' => 'indigo',
                'image' => 'https://m.media-amazon.com/images/I/71kBm7GwIkL.jpg',
                'gallery' => [
                    'https://cdn11.bigcommerce.com/s-lntro/images/stencil/original/products/18979/56696/UT-ALU-P1-B__22979.1608230167.jpg',
                    'https://m.media-amazon.com/images/I/712UcVtQ7mL.jpg',
                    'https://cdn11.bigcommerce.com/s-lntro/images/stencil/original/products/19126/56662/UT-ALU-P67-A__81022.1608229857.jpg',
                    'https://m.media-amazon.com/images/I/71CuI4WnUmL._AC_UF894,1000_QL80_.jpg',
                    'https://m.media-amazon.com/images/I/61IvUUsnbSL._AC_UF894,1000_QL80_.jpg',
                    'https://www.ofo-orlando.com/wp-content/uploads/2020/04/image1.png',
                    'https://cdn11.bigcommerce.com/s-lntro/images/stencil/500x659/products/19109/57270/UT-ALU-P61-B__15229.1608230506.jpg?c=2',
                    'https://www.alu-haomei.com/attachment/78/source/933361cd1b610e43601b130fdec27e86_aluminum_pipe_7_157752_157759.jpg',
                    'https://www.alu-wallcladding.com/uploads/202212692/metal-aluminum-room-divider-partitions-for27530769083.jpg',
                ],
                'features' => [
                    ['fr' => 'Robustesse', 'en' => 'Robustness', 'ar' => 'المتانة'],
                    ['fr' => 'Élégance du verre', 'en' => 'Glass elegance', 'ar' => 'أناقة الزجاج'],
                    ['fr' => 'Luminosité préservée', 'en' => 'Preserved brightness', 'ar' => 'الحفاظ على السطوع'],
                    ['fr' => 'Polyvalence', 'en' => 'Versatility', 'ar' => 'تعدد الاستخدامات'],
                    ['fr' => 'Installation facile', 'en' => 'Easy installation', 'ar' => 'تركيب سهل'],
                    ['fr' => 'Sans entretien', 'en' => 'No maintenance', 'ar' => 'بدون صيانة'],
                    ['fr' => 'Design contemporain', 'en' => 'Contemporary design', 'ar' => 'تصميم معاصر'],
                ],
                'materials' => [
                    ['fr' => 'Cloisons aluminium', 'en' => 'Aluminum partitions', 'ar' => 'فواصل الألومنيوم'],
                    ['fr' => 'Panneaux verre', 'en' => 'Glass panels', 'ar' => 'ألواح زجاجية'],
                    ['fr' => 'Systèmes portes', 'en' => 'Door systems', 'ar' => 'أنظمة الأبواب'],
                    ['fr' => 'Joints acoustiques', 'en' => 'Acoustic seals', 'ar' => 'حشوات صوتية'],
                ],
                'specs' => [
                    ['label' => 'Options verre', 'value' => '6 - 12 mm'],
                    ['label' => 'Hauteur max', 'value' => '3.5 m'],
                    ['label' => 'Couleurs', 'value' => '200+'],
                ],
                'sort_order' => 9,
            ],
        ];

        foreach ($services as $serviceData) {
            Service::updateOrCreate(
                ['slug' => $serviceData['slug']],
                array_merge($serviceData, ['is_active' => true])
            );
        }
    }
}
